In [1]:
# Exp No :2
#Aim: To find Central Tendancy  of Measures (Mean,Median,Mode).
#Name:Shrutika Mehare
#Roll No.:39
#Sec:B
#Subject:ET 1
#Date:31/07/2025

# Aim: To find Central Tendancy  of Measures (Mean,Median,Mode)

In [5]:
age=[21,20,22,23,23,22,22,20,20,21]

In [6]:
age

[21, 20, 22, 23, 23, 22, 22, 20, 20, 21]

In [14]:
import statistics 

In [15]:
A=statistics.mean(age)

In [16]:
A

21.4

In [17]:
print(A)

21.4


In [18]:
B =statistics.median(age)

In [19]:
B

21.5

In [20]:
C =statistics.mode(age)

In [21]:
C

20

In [22]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,2,6,2,1,4,2,2,6])

In [23]:
x

array([1, 2, 3, 4, 5, 6, 7, 2, 6, 2, 1, 4, 2, 2, 6])

In [24]:
print(np.mean(x))

3.533333333333333


In [25]:
print(np.median(x))

3.0


In [26]:
from scipy import stats

In [27]:
print(stats.mode(x))

ModeResult(mode=array([2]), count=array([5]))


In [31]:
print(np.var(x))

3.8488888888888884


In [32]:
std_dev = stats.tstd(x)

In [33]:
print("Standard Deviation:", std_dev)

Standard Deviation: 2.0307165050320353


In [34]:
variance = stats.tvar(x)

In [35]:
print("Variance:", variance)

Variance: 4.123809523809523


In [7]:
import numpy as np

In [8]:
a1=np.array([10,20,30,40])

In [9]:
a1

array([10, 20, 30, 40])

In [10]:
a2=np.array([[10,20,30,40],[60,70,80,90]])

In [11]:
a2

array([[10, 20, 30, 40],
       [60, 70, 80, 90]])

In [14]:
#3 dimensional array#

In [16]:
a3=np.array([[10,20,30,40],[60,70,80,90],[100,110,120,130]])

In [17]:
a3

array([[ 10,  20,  30,  40],
       [ 60,  70,  80,  90],
       [100, 110, 120, 130]])