In [1]:
# Exp No :5
#Aim: Creation of Array(1D,2D and Multidimensional array).
#Name:Shrutika Mehare
#Roll No.:39
#Sec:B
#Subject:ET 1
#Date:21/08/2025

# Aim: Creation of Array(1D,2D and Multidimensional array).

In [2]:
import numpy as np

# 1 Dimensional Array

In [3]:
arr1=np.array([10,20,30,40,50])

In [4]:
arr1

array([10, 20, 30, 40, 50])

# 2 Dimensional Array

In [5]:
arr2=([10,20,30,40,50],[60,70,80,90,100])

In [6]:
arr2

([10, 20, 30, 40, 50], [60, 70, 80, 90, 100])

# 3 Dimensional Array

In [20]:
arr3=np.array([[10,20,30,40,50],[60,70,80,90,100],[15,25,35,45,55]])

In [21]:
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 15,  25,  35,  45,  55]])

In [22]:
# Array of zeros
zeros_arr = np.zeros((2,3))
print("Zeros Array :\n",zeros_arr)

Zeros Array :
 [[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Array of ones
ones_arr = np.ones((3,3))
print("Ones Array :\n",ones_arr)

Ones Array :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# Identity Matrix
identity_arr = np.eye(3)
print("Identity Matrix :\n",identity_arr)

Identity Matrix :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# Range of Numbers
range_arr = np.arange(0,10,2)
print(" Array with np.arange:\n",range_arr)

 Array with np.arange:
 [0 2 4 6 8]


In [26]:
# Evenly spaced values
linspace_arr = np.linspace(0,1,5)
print("Array with np.linspace :\n",linspace_arr)

Array with np.linspace :
 [0.   0.25 0.5  0.75 1.  ]
